---
title: "Guia de Instalacion"
author: "Patricia Loto"
date: "16/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Antes del workshop

Gracias por inscribirte a este workshop, para aprovechar el mismo por favor, trae una pc portátil con lo siguiente instalado:

* Una versión reciente de R (>=3.6.1), el cual está disponible de manera gratuita para su descarga en CRAN [https://cran.r-project.org/]. Ten cuenta la versión de tu sistema operativo para descargar la correcta.

* Una versión reciente de Rstudio Desktop (>=1.2.5033), disponible de manera gratuita para su descarga en Rstudio [https://www.rstudio.com/download].Ten cuenta la versión de tu sistema operativo (32 o 64 bits)para descargar la correcta.

Los paquetes que utilizaremos, los cuales pueden instalarse
abriendo Rstudio y ejecutando las siguientes sentencias:

Para poder instalar de manera exitosa los paquetes, es necesario que estés conectado a Internet.

Espero conocerte pronto,

Patricia

----------------------------------------
